<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.muhammaddaffa</groupId>
    <artifactId>PlayerProfiles</artifactId>
    <packaging>pom</packaging>
    <version>8.0.5</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spigot.version>1.21.11-R0.1-SNAPSHOT</spigot.version>
        <worldguard.version>7.0.10</worldguard.version>
        <worldedit.version>7.3.12</worldedit.version>
    </properties>

    <modules>
        <module>dist</module>
        <module>core</module>
        <module>api</module>
        <module>worldguard-wrapper</module>
        <module>worldguard7</module>
    </modules>

</project>