name: PlayerProfiles
version: 8.0.5
main: com.muhammaddaffa.playerprofiles.PlayerProfiles
author: aglerr, Starfruit2210
description: Plugin to show player profiles
api-version: 1.21
softdepend: [CombatLogX, DeluxeCombat, PlaceholderAPI, WorldGuard, WorldEdit]

commands:
  playerprofiles:
    aliases: []
  profile:
    aliases: []
  unlockProfile:
    aliases: []
  lockProfile:
    aliases: []
  toggleprofile:
    aliases: []